version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: ecs-cpu-test
    AWS_DEFAULT_REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "Exporting IMAGE_URI for CodePipeline"
      # This is the key step to make it available as a pipeline variable
      - echo "IMAGE_URI=$IMAGE_URI" >> variables.env

artifacts:
  files:
    - variables.env
  name: BuildOutput
  discard-paths: yes
  # Important: this makes IMAGE_URI available as BuildOutput.IMAGE_URI
