version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: ecs-cpu-test
    AWS_DEFAULT_REGION: ap-south-1
    CFN_ARTIFACT_BUCKET: ecs-cpu-artifacts-140857882741
  exported-variables:
    - IMAGE_URI

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI -f docker/Dockerfile .

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $IMAGE_URI
      - echo "Packaging CloudFormation templates..."
      - aws cloudformation package \
          --template-file devops/main.yaml \
          --s3-bucket $CFN_ARTIFACT_BUCKET \
          --output-template-file packaged.yaml
      - echo "IMAGE_URI=$IMAGE_URI"

artifacts:
  files:
    - packaged.yaml
