version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: ecs-cpu-test
    AWS_DEFAULT_REGION: ap-south-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo $IMAGE_URI
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .
      - docker push $IMAGE_URI
      - echo "IMAGE_URI=$IMAGE_URI" > image-detail.txt

artifacts:
  files:
    - image-detail.txt
  name: BuildOutput
  # This makes IMAGE_URI available as a CodePipeline variable
